# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pyqt/qt_designer_generate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 861)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(920, 130, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.target = QtWidgets.QLabel(self.centralwidget)
        self.target.setGeometry(QtCore.QRect(120, 110, 768, 512))
        self.target.setText("")
        self.target.setPixmap(QtGui.QPixmap("default-video.jpg"))
        self.target.setScaledContents(True)
        self.target.setObjectName("target")
        self.logo_ftech = QtWidgets.QLabel(self.centralwidget)
        self.logo_ftech.setGeometry(QtCore.QRect(47, 650, 371, 141))
        self.logo_ftech.setText("")
        self.logo_ftech.setPixmap(QtGui.QPixmap("ftech.png"))
        self.logo_ftech.setScaledContents(True)
        self.logo_ftech.setObjectName("logo_ftech")
        self.logo_dtvt = QtWidgets.QLabel(self.centralwidget)
        self.logo_dtvt.setGeometry(QtCore.QRect(480, 650, 161, 141))
        self.logo_dtvt.setText("")
        self.logo_dtvt.setPixmap(QtGui.QPixmap("dtvt.jpeg"))
        self.logo_dtvt.setScaledContents(True)
        self.logo_dtvt.setObjectName("logo_dtvt")
        self.svtt_1 = QtWidgets.QLabel(self.centralwidget)
        self.svtt_1.setGeometry(QtCore.QRect(697, 720, 221, 31))
        self.svtt_1.setObjectName("svtt_1")
        self.svtt_2 = QtWidgets.QLabel(self.centralwidget)
        self.svtt_2.setGeometry(QtCore.QRect(749, 750, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.svtt_2.setFont(font)
        self.svtt_2.setObjectName("svtt_2")
        self.gvhd_1 = QtWidgets.QLabel(self.centralwidget)
        self.gvhd_1.setGeometry(QtCore.QRect(697, 650, 241, 31))
        self.gvhd_1.setObjectName("gvhd_1")
        self.gvhd_2 = QtWidgets.QLabel(self.centralwidget)
        self.gvhd_2.setGeometry(QtCore.QRect(750, 680, 171, 41))
        self.gvhd_2.setObjectName("gvhd_2")
        self.detai = QtWidgets.QLabel(self.centralwidget)
        self.detai.setGeometry(QtCore.QRect(20, 10, 971, 81))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.detai.setFont(font)
        self.detai.setObjectName("detai")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 24))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionWebcam = QtWidgets.QAction(MainWindow)
        self.actionWebcam.setObjectName("actionWebcam")
        self.menuOpen.addAction(self.actionFile)
        self.menuOpen.addAction(self.actionWebcam)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Đồ án tốt nghiệp"))
        self.start.setText(_translate("MainWindow", "ON/OFF"))
        self.svtt_1.setText(_translate("MainWindow", "SVTT :  Đỗ Tuấn Sơn - 17DT3"))
        self.svtt_2.setText(_translate("MainWindow", "Nguyễn Phước Toàn - 17DT2"))
        self.gvhd_1.setText(_translate("MainWindow", "GVHD : TS. Phan Trần Đăng Khoa"))
        self.gvhd_2.setText(_translate("MainWindow", "ThS. Doãn Đạt Phước"))
        self.detai.setText(_translate("MainWindow", "Tách chủ thể ra khỏi phông nền thời gian thực"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionWebcam.setText(_translate("MainWindow", "Webcam"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

